### ISSUE TITLE
No solution or curriculum branch

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/dsc-xgboost-deloitte-lab#2]
## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

Need to find the solutions for this and add them to a solution branch. Could be easiest to start over from a new curriculum branch and go from there. 

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
They are there.
